# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMVVMExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMVVMExample

  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'Then',       '~> 2.1'
  pod 'Toaster',    '~> 2.0'

  target 'RxMVVMExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxMVVMExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
